version: "2.2"
services:
    db:
        container_name: mydb
        image: mysql:8.0.31
        ports:
            - "32001:3306"
        environment:
            MYSQL_ROOT_PASSWORD: password
    app:
        container_name: myapp
        links:
            - "db"
        build: ./
        ports:
            - "5001:5000"
